apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slurm
  namespace: argocd
spec:
  project: default
  source:
    chart: slurm
    repoURL: ghcr.io/slinkyproject/charts
    targetRevision: "0.3.0"
    helm:
      values: |
        ${slurm_values}
  destination:
    server: https://kubernetes.default.svc
    namespace: slurm
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
