# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: trtllm-engine-config-high-performance
  labels:
    app: trtllm
    config-type: engine
    variant: high-performance
data:
  agg.yaml: |
    # High-Performance TensorRT-LLM Engine Configuration
    # Optimized for maximum throughput and lowest latency
    # Based on the actual working configuration from dynamo/components/backends/trtllm/engine_configs/agg.yaml
    tensor_parallel_size: 1
    moe_expert_parallel_size: 1
    enable_attention_dp: false
    max_num_tokens: 16384
    max_batch_size: 32
    trust_remote_code: true
    backend: pytorch
    enable_chunked_prefill: true

    kv_cache_config:
      free_gpu_memory_fraction: 0.90

    cuda_graph_config:
      max_batch_size: 32