
# NOTE: Using Ubuntu to use latest version of GPU Operator, this is for time slicing enable
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: inferentia
  namespace: karpenter
spec:
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand" ]
    - key: "node.kubernetes.io/instance-type" # For P4d we can use MIG since it uses A100
      operator: In
      values: ["inf2.24xlarge", "inf2.48xlarge"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
  providerRef:
    name: inferentia
  labels:
    provisioner: inferentia
    hub.jupyter.org/node-purpose: user
  taints:
    - key: aws.amazon.com/neuroncore
      value: "true"
      effect: "NoSchedule"
    - key: aws.amazon.com/neuron
      value: "true"
      effect: "NoSchedule"
    - key: hub.jupyter.org/dedicated # According to optimization docs https://z2jh.jupyter.org/en/latest/administrator/optimization.html
      operator: "Equal"
      value: "user"
      effect: "NoSchedule"
  ttlSecondsAfterEmpty: 300 # optional, but never scales down if not set

# Add this to the node
# # Install Neuron monitoring tools
# yum install aws-neuronx-tools-2.* -y
# export PATH=/opt/aws/neuron/bin:$PATH
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: inferentia
  namespace: karpenter
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 200Gi # Big disk for Notebook instances
        volumeType: gp3
        encrypted: true
  subnetSelector:
    Name: ${eks_cluster_id}-private*     # Name of the Subnets to spin up the nodes
  securityGroupSelector:                      # required, when not using launchTemplate
    Name: ${eks_cluster_id}-node*     # name of the SecurityGroup to be used with Nodes
  tags:
    InstanceType: "inferentia"