{{- if eq .Values.inference.framework "rayVllm" }}
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: {{.Values.inference.serviceName}}-{{ .Values.inference.accelerator }}-ray-vllm
  namespace: {{.Values.inference.serviceNamespace}}
spec:
  deploymentUnhealthySecondThreshold: 900
  rayClusterConfig:
    headGroupSpec:
      headService:
        metadata:
          name: {{.Values.inference.serviceName}}-{{ .Values.inference.accelerator }}-ray-vllm
          namespace: {{.Values.inference.serviceNamespace}}
      rayStartParams:
        dashboard-host: 0.0.0.0
        num-cpus: '0'
      template:
        spec:
          containers:
            - env:
                - name: HUGGING_FACE_HUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: token
                      name: hf-token
                - name: LD_LIBRARY_PATH
                  value: /home/ray/anaconda3/lib
                - name: RAY_GRAFANA_HOST
                  value: {{ .Values.inference.observability.rayGrafanaHost }}
                - name: RAY_PROMETHEUS_HOST
                  value: {{ .Values.inference.observability.rayPrometheusHost }}
                - name: RAY_GRAFANA_IFRAME_HOST
                  value: {{ .Values.inference.observability.rayGrafanaIframeHost }}
              image: "{{ .Values.inference.modelServer.image.repository }}:{{ .Values.inference.modelServer.image.tag }}"
              imagePullPolicy: {{ .Values.global.image.pullPolicy }}
              lifecycle:
                preStop:
                  exec:
                    command:
                      - /bin/sh
                      - '-c'
                      - ray stop
              name: head
              ports:
                - containerPort: 6379
                  name: gcs
                  protocol: TCP
                - containerPort: 8265
                  name: dashboard
                  protocol: TCP
                - containerPort: 10001
                  name: client
                  protocol: TCP
                - containerPort: 8000
                  name: serve
                  protocol: TCP
              resources:
                limits:
                  cpu: 4
                  memory: 20Gi
                requests:
                  cpu: 4
                  memory: 20Gi
              volumeMounts:
                - mountPath: /tmp/ray
                  name: ray-logs
                - mountPath: /home/ray/vllm_serve.py
                  subPath: vllm_serve.py
                  name: vllm-script
            - name: fluentbit
              image: {{ .Values.fluentbit.image.repository }}:{{ .Values.fluentbit.image.tag }}
              env:
                - name: POD_LABELS
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['ray.io/cluster']
              resources:
                {{- toYaml .Values.fluentbit.resources | nindent 18 }}
              volumeMounts:
                - mountPath: /tmp/ray
                  name: ray-logs
                - mountPath: /fluent-bit/etc/fluent-bit.conf
                  subPath: fluent-bit.conf
                  name: fluentbit-config
          volumes:
            - emptyDir: {}
              name: ray-logs
            - configMap:
                items:
                  - key: vllm_serve.py
                    path: vllm_serve.py
                name: ray-vllm-serve
              name: vllm-script
            - name: fluentbit-config
              configMap:
                name: fluentbit-config
    rayVersion: {{ .Values.inference.modelServer.rayVersion }}
    workerGroupSpecs:
      - groupName: worker
        maxReplicas: {{ .Values.inference.modelServer.deployment.maxReplicas }}
        minReplicas: {{ .Values.inference.modelServer.deployment.minReplicas }}
        numOfHosts: 1
        rayStartParams: {}
        replicas: {{ .Values.inference.modelServer.deployment.replicas }}
        template:
          spec:
            containers:
              - env:
                  - name: LD_LIBRARY_PATH
                    value: /home/ray/anaconda3/lib
                  - name: VLLM_PORT
                    value: '{{ .Values.vllm.port }}'
                  - name: VLLM_LOGGING_LEVEL
                    value: {{ .Values.vllm.logLevel }}
                  - name: HUGGING_FACE_HUB_TOKEN
                    valueFrom:
                      secretKeyRef:
                        key: token
                        name: hf-token
                  {{- if .Values.modelParameters }}
                  {{- range $key, $value := .Values.modelParameters }}
                  - name: {{ $key | snakecase | upper }}
                    value: "{{ $value }}"
                  {{- end }}
                  {{- end }}
                  {{- if eq .Values.inference.accelerator "neuron" }}
                  - name: NEURON_CC_FLAGS
                    value: "-O1"
                  {{- end }}
                image: "{{ .Values.inference.modelServer.image.repository }}:{{ .Values.inference.modelServer.image.tag }}{{ if eq .Values.inference.accelerator "gpu" }}-gpu{{ end }}"
                imagePullPolicy: {{ .Values.global.image.pullPolicy }}
                lifecycle:
                  preStop:
                    exec:
                      command:
                        - /bin/sh
                        - '-c'
                        - ray stop
                name: worker
                resources:
                  {{- if eq .Values.inference.accelerator "gpu" }}
                  {{- toYaml .Values.inference.modelServer.deployment.resources.gpu | nindent 18 }}
                  {{- else }}
                  {{- toYaml .Values.inference.modelServer.deployment.resources.neuron | nindent 18 }}
                  {{- end }}
                volumeMounts:
                  - mountPath: /tmp/ray
                    name: ray-logs
              - name: fluentbit
                image: {{ .Values.fluentbit.image.repository }}:{{ .Values.fluentbit.image.tag }}
                env:
                  - name: POD_LABELS
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.labels['ray.io/cluster']
                resources:
                  {{- toYaml .Values.fluentbit.resources | nindent 18 }}
                volumeMounts:
                  - mountPath: /tmp/ray
                    name: ray-logs
                  - mountPath: /fluent-bit/etc/fluent-bit.conf
                    subPath: fluent-bit.conf
                    name: fluentbit-config
            {{- if eq .Values.inference.accelerator "gpu" }}
            tolerations:
              - key: nvidia.com/gpu
                operator: Exists
                effect: NoSchedule
            {{- else }}
            tolerations:
              - key: "aws.amazon.com/neuron"
                operator: "Exists"
                effect: "NoSchedule"
            {{- end }}
            {{- if .Values.inference.modelServer.deployment.instanceType }}
            nodeSelector:
              beta.kubernetes.io/instance-type: {{ .Values.inference.modelServer.deployment.instanceType }}
            {{- end }}
            volumes:
              - emptyDir: {}
                name: ray-logs
              - name: fluentbit-config
                configMap:
                  name: fluentbit-config
  serveConfigV2: |
    applications:
      - name: serve
        import_path: vllm_serve:deployment
        {{- if eq .Values.inference.accelerator "gpu" }}
        runtime_env:
          pip:
            - vllm=={{.Values.inference.modelServer.vllmVersion}}
        {{- end }}
        deployments:
          - name: serve
            ray_actor_options:
              {{- if eq .Values.inference.accelerator "gpu" }}
              num_gpus: {{ .Values.modelParameters.numGpus }}
              {{- else }}
              resources: {"neuron_cores": {{ mul .Values.modelParameters.numGpus 2 }}}
              {{- end }}
  serviceUnhealthySecondThreshold: 900
{{- end }}
