# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: sglang-disaggregated-70b
  namespace: dynamo-cloud
spec:
  services:
    Frontend:
      dynamoNamespace: sglang-disaggregated-70b
      componentType: frontend
      replicas: 1
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - 'curl -s http://localhost:8000/health | jq -e ".status == \"healthy\""'
        initialDelaySeconds: 60
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:0.4.1
          workingDir: /workspace/components/backends/sglang
          command:
            - /bin/sh
            - -c
          args:
            - "python3 -m dynamo.frontend --http-port 8000"
    SglangDecodeWorker:
      dynamoNamespace: sglang-disaggregated-70b
      envFromSecret: hf-token-secret
      componentType: worker
      replicas: 1
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - "exit 0"
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - "exit 0"
        initialDelaySeconds: 60
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      resources:
        requests:
          cpu: "16"
          memory: "64Gi"
          gpu: "4"
        limits:
          cpu: "16"
          memory: "64Gi"
          gpu: "4"
      extraPodSpec:
        nodeSelector:
          karpenter.sh/nodepool: g6-gpu-karpenter
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:0.4.1
          workingDir: /workspace/components/backends/sglang
          command:
            - /bin/sh
            - -c
          args:
            - "python3 -m dynamo.sglang --model-path nvidia/Llama-3.3-70B-Instruct-FP8 --served-model-name nvidia/Llama-3.3-70B-Instruct-FP8 --page-size 16 --tp 4 --trust-remote-code --skip-tokenizer-init --disaggregation-mode decode --disaggregation-transfer-backend nixl"
    SglangPrefillWorker:
      dynamoNamespace: sglang-disaggregated-70b
      envFromSecret: hf-token-secret
      componentType: worker
      replicas: 1
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - "exit 0"
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - "exit 0"
        initialDelaySeconds: 60
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      resources:
        requests:
          cpu: "16"
          memory: "64Gi"
          gpu: "4"
        limits:
          cpu: "16"
          memory: "64Gi"
          gpu: "4"
      extraPodSpec:
        nodeSelector:
          karpenter.sh/nodepool: g6-gpu-karpenter
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:0.4.1
          workingDir: /workspace/components/backends/sglang
          command:
            - /bin/sh
            - -c
          args:
            - "python3 -m dynamo.sglang --model-path nvidia/Llama-3.3-70B-Instruct-FP8 --served-model-name nvidia/Llama-3.3-70B-Instruct-FP8 --page-size 16 --tp 4 --trust-remote-code --skip-tokenizer-init --disaggregation-mode prefill --disaggregation-transfer-backend nixl"
