# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: trtllm-prefill-config
  namespace: dynamo-cloud
  labels:
    app: trtllm-disagg
    config-type: engine
    variant: prefill
data:
  prefill.yaml: |
    # TensorRT-LLM Prefill Worker Configuration
    # Based on the actual working configuration from dynamo/components/backends/trtllm/engine_configs/prefill.yaml
    tensor_parallel_size: 1
    moe_expert_parallel_size: 1
    enable_attention_dp: false
    max_num_tokens: 8192
    trust_remote_code: true
    backend: pytorch
    enable_chunked_prefill: true
    # Overlap scheduler not currently supported in prefill only workers.
    disable_overlap_scheduler: true
    
    cuda_graph_config:
      max_batch_size: 16
    
    kv_cache_config:
      free_gpu_memory_fraction: 0.85

    cache_transceiver_config:
      backend: default
