# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: sglang-disagg
spec:
  services:
    Frontend:
      dynamoNamespace: sglang-disagg
      componentType: main
      replicas: 1
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - "exit 0"
        initialDelaySeconds: 60
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:v0.4.0
          workingDir: /workspace/components/backends/sglang
          command: ["sh", "-c"]
          args:
            - "python3 -m dynamo.sglang.utils.clear_namespace --namespace sglang-disagg && python3 -m dynamo.frontend --http-port=8000"
    SGLangDecodeWorker:
      dynamoNamespace: sglang-disagg
      envFromSecret: hf-token-secret
      componentType: worker
      replicas: 2
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - "exit 0"
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - "exit 0"
        initialDelaySeconds: 60
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      resources:
        requests:
          cpu: "8"
          memory: "20Gi"
          gpu: "1"
        limits:
          cpu: "8"
          memory: "20Gi"
          gpu: "1"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:v0.4.0
          workingDir: /workspace/components/backends/sglang
          args:
            - "python3"
            - "-m"
            - "dynamo.sglang.decode_worker"
            - "--model-path"
            - "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"
            - "--served-model-name"
            - "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"
            - "--page-size"
            - "16"
            - "--tp"
            - "1"
            - "--trust-remote-code"
            - "--skip-tokenizer-init"
            - "--disaggregation-mode"
            - "decode"
            - "--disaggregation-transfer-backend"
            - "nixl"
    SGLangPrefillWorker:
      dynamoNamespace: sglang-disagg
      envFromSecret: hf-token-secret
      componentType: worker
      replicas: 1
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - "exit 0"
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - "exit 0"
        initialDelaySeconds: 60
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      resources:
        requests:
          cpu: "8"
          memory: "20Gi"
          gpu: "1"
        limits:
          cpu: "8"
          memory: "20Gi"
          gpu: "1"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:v0.4.0
          workingDir: /workspace/components/backends/sglang
          args:
            - "python3"
            - "-m"
            - "dynamo.sglang.worker"
            - "--model-path"
            - "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"
            - "--served-model-name"
            - "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"
            - "--page-size"
            - "16"
            - "--tp"
            - "1"
            - "--trust-remote-code"
            - "--skip-tokenizer-init"
            - "--disaggregation-mode"
            - "prefill"
            - "--disaggregation-transfer-backend"
            - "nixl"