# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: trtllm-aggregated-70b
  namespace: dynamo-cloud
spec:
  services:
    Frontend:
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - 'curl -s http://localhost:8000/health | jq -e ".status == \"healthy\""'
        initialDelaySeconds: 60
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      dynamoNamespace: trtllm-aggregated-70b
      componentType: main
      replicas: 1
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/tensorrtllm-runtime:0.4.1
          workingDir: /workspace/components/backends/trtllm
          command:
            - /bin/sh
            - -c
          args:
            - "python3 -m dynamo.frontend --http-port 8000"
    TRTLLMWorker:
      envFromSecret: hf-token-secret
      livenessProbe:
        httpGet:
          path: /live
          port: 9090
        periodSeconds: 5
        timeoutSeconds: 30
        failureThreshold: 1
      readinessProbe:
        httpGet:
          path: /health
          port: 9090
        periodSeconds: 10
        timeoutSeconds: 30
        failureThreshold: 60
      dynamoNamespace: trtllm-aggregated-70b
      componentType: worker
      replicas: 1
      resources:
        requests:
          cpu: "32"
          memory: "128Gi"
          gpu: "8"
        limits:
          cpu: "32"
          memory: "128Gi"
          gpu: "8"
      envs:
        - name: DYN_SYSTEM_ENABLED
          value: "true"
        - name: DYN_SYSTEM_USE_ENDPOINT_HEALTH_STATUS
          value: "[\"generate\"]"
        - name: DYN_SYSTEM_PORT
          value: "9090"
      extraPodSpec:
        imagePullSecrets:
          - name: ngc-secret
        nodeSelector:
          karpenter.sh/nodepool: g6-gpu-karpenter
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/tensorrtllm-runtime:0.4.1
          workingDir: /workspace/components/backends/trtllm
          startupProbe:
            httpGet:
              path: /health
              port: 9090
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 300
          command:
            - /bin/sh
            - -c
          args:
            - |
              # Create inline engine configuration for 70B model
              mkdir -p /tmp/engine_configs
              cat > /tmp/engine_configs/agg.yaml << 'EOF'
              # 70B Model TensorRT-LLM Engine Configuration
              # Optimized for nvidia/Llama-3.3-70B-Instruct-FP8
              tensor_parallel_size: 8
              pipeline_parallel_size: 1
              moe_expert_parallel_size: 1
              enable_attention_dp: false
              max_num_tokens: 28800
              max_batch_size: 8
              trust_remote_code: true
              backend: pytorch
              enable_chunked_prefill: true
              
              kv_cache_config:
                free_gpu_memory_fraction: 0.85
              
              cuda_graph_config:
                max_batch_size: 8
              EOF
              
              # Start TensorRT-LLM worker with 70B model
              python3 -m dynamo.trtllm --model-path nvidia/Llama-3.3-70B-Instruct-FP8 --served-model-name nvidia/Llama-3.3-70B-Instruct-FP8 --extra-engine-args /tmp/engine_configs/agg.yaml
