# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: trtllm
  namespace: dynamo-cloud
spec:
  services:
    Frontend:
      dynamoNamespace: trtllm
      componentType: main
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - 'curl -s http://localhost:8000/health | jq -e ".status == \"healthy\""'
        periodSeconds: 5
        timeoutSeconds: 3
        failureThreshold: 3
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - 'curl -s http://localhost:8000/health | jq -e ".status == \"healthy\""'
        initialDelaySeconds: 60
        periodSeconds: 60
        timeoutSeconds: 3
        failureThreshold: 10
      replicas: 1
      resources:
        requests:
          cpu: "5"
          memory: "10Gi"
        limits:
          cpu: "5"
          memory: "10Gi"
      extraPodSpec:
        imagePullSecrets:
          - name: ngc-secret
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/tensorrtllm-runtime:0.4.1
          workingDir: /workspace/components/backends/trtllm
          command:
            - /bin/sh
            - -c
          args:
            - "python3 -m dynamo.frontend --http-port 8000"
    TRTLLMWorker:
      envFromSecret: hf-token-secret
      livenessProbe:
        httpGet:
          path: /live
          port: 9090
        periodSeconds: 5
        timeoutSeconds: 3
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /health
          port: 9090
        periodSeconds: 10
        timeoutSeconds: 3
        failureThreshold: 60
      dynamoNamespace: trtllm
      componentType: worker
      replicas: 1
      resources:
        requests:
          cpu: "10"
          memory: "20Gi"
          gpu: "1"
        limits:
          cpu: "10"
          memory: "20Gi"
          gpu: "1"
      envs:
        - name: DYN_SYSTEM_ENABLED
          value: "true"
        - name: DYN_SYSTEM_USE_ENDPOINT_HEALTH_STATUS
          value: "[\"generate\"]"
        - name: DYN_SYSTEM_PORT
          value: "9090"
      extraPodSpec:
        imagePullSecrets:
          - name: ngc-secret
        nodeSelector:
          karpenter.sh/nodepool: g5-gpu-karpenter
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        # Volume definition for engine configuration from ConfigMap
        volumes:
          - name: engine-config-volume
            configMap:
              name: trtllm-engine-config-default  # Use trtllm-engine-config-high-performance for high-perf
              items:
                - key: agg.yaml
                  path: agg.yaml
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/tensorrtllm-runtime:0.4.1
          workingDir: /workspace/components/backends/trtllm
          startupProbe:
            httpGet:
              path: /health
              port: 9090
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 60
          # Volume mount for external configurations
          volumeMounts:
            - name: engine-config-volume
              mountPath: /workspace/components/backends/trtllm/external_configs
              readOnly: true
          args:
            - "python3 -m dynamo.trtllm --model-path Qwen/Qwen3-0.6B --served-model-name Qwen/Qwen3-0.6B --extra-engine-args external_configs/agg.yaml"
