# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: trtllm-disaggregated-high-performance
  namespace: dynamo-cloud
spec:
  services:
    Frontend:
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - 'curl -s http://localhost:8000/health | jq -e ".status == \"healthy\""'
        initialDelaySeconds: 60
        periodSeconds: 60
        timeoutSeconds: 30
        failureThreshold: 10
      dynamoNamespace: trtllm-disaggregated-high-performance
      componentType: main
      replicas: 1
      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/tensorrtllm-runtime:0.4.1
          workingDir: /workspace/components/backends/trtllm
          command:
            - /bin/sh
            - -c
          args:
            - "python3 -m dynamo.frontend --http-port 8000"
    TRTLLMDecodeWorker:
      dynamoNamespace: trtllm-disaggregated-high-performance
      envFromSecret: hf-token-secret
      componentType: worker
      replicas: 1
      livenessProbe:
        httpGet:
          path: /live
          port: 9090
        periodSeconds: 5
        timeoutSeconds: 3
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /health
          port: 9090
        periodSeconds: 10
        timeoutSeconds: 3
        failureThreshold: 120
      resources:
        requests:
          cpu: "16"
          memory: "32Gi"
          gpu: "1"
        limits:
          cpu: "16"
          memory: "32Gi"
          gpu: "1"
      envs:
        - name: DYN_SYSTEM_ENABLED
          value: "true"
        - name: DYN_SYSTEM_USE_ENDPOINT_HEALTH_STATUS
          value: "[\"generate\"]"
        - name: DYN_SYSTEM_PORT
          value: "9090"
      extraPodSpec:
        imagePullSecrets:
          - name: ngc-secret
        nodeSelector:
          karpenter.sh/nodepool: g5-gpu-karpenter
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        mainContainer:
          startupProbe:
            httpGet:
              path: /health
              port: 9090
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 120
          image: nvcr.io/nvidia/ai-dynamo/tensorrtllm-runtime:0.4.1
          workingDir: /workspace/components/backends/trtllm
          command:
            - /bin/sh
            - -c
          args:
            - |
              # Create inline decode configuration for high performance
              mkdir -p /tmp/engine_configs
              cat > /tmp/engine_configs/decode.yaml << 'EOF'
              # High-Performance TensorRT-LLM Decode Worker Configuration
              tensor_parallel_size: 1
              moe_expert_parallel_size: 1
              enable_attention_dp: false
              max_num_tokens: 16384
              trust_remote_code: true
              backend: pytorch
              enable_chunked_prefill: true
              disable_overlap_scheduler: false
              
              cuda_graph_config:
                max_batch_size: 32
              
              kv_cache_config:
                free_gpu_memory_fraction: 0.90
              
              cache_transceiver_config:
                backend: default
              EOF
              
              # Start TensorRT-LLM decode worker
              python3 -m dynamo.trtllm --model-path Qwen/Qwen3-0.6B --served-model-name Qwen/Qwen3-0.6B --extra-engine-args /tmp/engine_configs/decode.yaml --disaggregation-mode decode --disaggregation-strategy decode_first
    TRTLLMPrefillWorker:
      dynamoNamespace: trtllm-disaggregated-high-performance
      envFromSecret: hf-token-secret
      componentType: worker
      replicas: 1
      livenessProbe:
        httpGet:
          path: /live
          port: 9090
        periodSeconds: 5
        timeoutSeconds: 3
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /health
          port: 9090
        periodSeconds: 10
        timeoutSeconds: 3
        failureThreshold: 120
      resources:
        requests:
          cpu: "16"
          memory: "32Gi"
          gpu: "1"
        limits:
          cpu: "16"
          memory: "32Gi"
          gpu: "1"
      envs:
        - name: DYN_SYSTEM_ENABLED
          value: "true"
        - name: DYN_SYSTEM_USE_ENDPOINT_HEALTH_STATUS
          value: "[\"generate\"]"
        - name: DYN_SYSTEM_PORT
          value: "9090"
      extraPodSpec:
        imagePullSecrets:
          - name: ngc-secret
        nodeSelector:
          karpenter.sh/nodepool: g5-gpu-karpenter
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        mainContainer:
          startupProbe:
            httpGet:
              path: /health
              port: 9090
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 120
          image: nvcr.io/nvidia/ai-dynamo/tensorrtllm-runtime:0.4.1
          workingDir: /workspace/components/backends/trtllm
          command:
            - /bin/sh
            - -c
          args:
            - |
              # Create inline prefill configuration for high performance
              mkdir -p /tmp/engine_configs
              cat > /tmp/engine_configs/prefill.yaml << 'EOF'
              # High-Performance TensorRT-LLM Prefill Worker Configuration
              tensor_parallel_size: 1
              moe_expert_parallel_size: 1
              enable_attention_dp: false
              max_num_tokens: 16384
              trust_remote_code: true
              backend: pytorch
              enable_chunked_prefill: true
              # Overlap scheduler not currently supported in prefill only workers
              disable_overlap_scheduler: true

              cuda_graph_config:
                max_batch_size: 32

              kv_cache_config:
                free_gpu_memory_fraction: 0.90

              cache_transceiver_config:
                backend: default
              EOF

              # Start TensorRT-LLM prefill worker
              python3 -m dynamo.trtllm --model-path Qwen/Qwen3-0.6B --served-model-name Qwen/Qwen3-0.6B --extra-engine-args /tmp/engine_configs/prefill.yaml --disaggregation-mode prefill --disaggregation-strategy decode_first
